# Generated by Django 4.2.7 on 2023-11-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_banner_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="sub_comment", new_name="sub_comments",
        ),
    ]
