# Generated by Django 4.2.7 on 2023-11-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_sub_comment_comment_sub_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
